#!/usr/bin/env ruby

ARGV.size == 1 or raise ArgumentError, "usage: #{File.basename $0} <message>"
message = ARGV.first

width = message.size + 2 * 2
horizontal_border = '+' << '-' * (width - 2) << '+'
puts horizontal_border
puts '| ' << message << ' |'
puts horizontal_border
