#!/usr/bin/env bash

progname=$(basename "$0")
volume="WD6"

disk=$(diskutil list | grep " $volume " | egrep -o 'disk\d')

if [ -z "$disk" ]; then
  terminal-notifier -title "$progname" -message "Couldn't find $volume"
  exit 1
fi

terminal-notifier -title "$progname" -message "Ejecting ${volume}..."
exec diskutil eject /dev/$disk
