#!/usr/bin/env bash

exec sudo find -x "$@" \
  -not -path '/Volumes/*' \
  -not -path '/private/var/db/BootCaches/*' \
  -not -path '/private/var/db/receipts/*' \
  -not -path '/Library/Logs/DiagnosticReports/*' \
  -not -path '/Library/Caches/*' \
  -not -path '/private/var/folders/*' \
  -not -path "$HOME"'/.Trash/*' \
  -not -path "$HOME"'/.npm/*' \
  -not -path "$HOME"'/Library/Caches/*' \
  -not -path "$HOME"'/Library/Saved Application State/*' \
  -not -path "$HOME"'/Library/Application Support/CrashReporter/*' \
  -not -path "$HOME"'/Library/Application Support/Cyberduck/History/*' \
  -not -path "$HOME"'/Library/Application Support/Google/Chrome/Default/Local Storage/*' \
  -not -path "$HOME"'/Library/Logs/CrashReporter/*' \
  -not -path "$HOME"'/Library/Preferences/Macromedia/Flash Player/*' \
  -not -path "$HOME"'/Library/Preferences/Macromedia/Flash Player/macromedia.com/support/flashplayer/sys/*' \
  -not -path "$HOME"'/Library/Safari/LocalStorage/*'
