#!/usr/bin/env bash

progname=$(basename "$0")
volume="_"

do_mnt() {
  mntwd6 \
    && open /Volumes/WD6/roman/_.dmg
}

do_open() {
  while ! [ -d /Volumes/$volume ]; do sleep 0.5; done \
    && open /Volumes/$volume
}

err=$(do_mnt 2>&1)
if [ $? != 0 ]; then
  terminal-notifier -title "$progname" -message "$err"
  exit 1
fi

terminal-notifier -title "$progname" -message "Opening ${volume}..."
do_open
