#!/usr/bin/env bash

progname=$(basename "$0")
volume="WD6"

part=$(diskutil list | grep " $volume " | egrep -o 'disk\d\w+')
if [ -z "$part" ]; then
  terminal-notifier -title "$progname" -message "Couldn't find $volume"
  exit 1
fi

terminal-notifier -title "$progname" -message "Mounting ${volume}..."
exec diskutil mount /dev/$part
