#!/usr/bin/env bash

progname=$(basename "$0")

terminal-notifier -title "$progname" -message "Mounting..."

err=$(diskutil mount /dev/disk2s2 2>&1)

if [ $? = 0 ]; then
  terminal-notifier -title "$progname" -message "Opening..."
  exec open /Volumes/WD6
else
  terminal-notifier -title "$progname" -message "$err"
fi
