#!/usr/bin/env bash

size=1024 # MB
mount_point=$HOME/tmp
name=$(basename "$mount_point")

usage() {
  echo "usage: $(basename "$0") [mount | umount | orphan] (default: mount)" >&2
  exit 1
}

process_argv() {
  [ $# -ge 0 -a $# -le 1 ] || usage
  case "$1" in
    "")       mount_tmp_mount ;;
    "mount")  mount_tmp_mount ;;
    "umount") mount_tmp_umount ;;
    "orphan") mount_tmp_orphan ;;
    *)        usage ;;
  esac
}

mount_tmp_mount() {
  if mount | grep -q " on $mount_point "; then
    echo "Already mounted at $mount_point" >&2
    return 1
  fi

  sectors=$(( $size * 1024 * 1024 / 512 ))
  dev=$(hdiutil attach -nomount ram://$sectors) \
    && newfs_hfs -v "$name" $dev \
    && mount -t hfs -o nobrowse $dev "$mount_point" \
    && echo "Hello, world!" > "$mount_point"/hello_world \
    && echo "Mounted $name ($size MB) at $mount_point"
}

mount_tmp_umount() {
  dev=$(df "$mount_point" | tail -1 | awk '{ print $1 }')
  [ $dev ] || return 1
  umount "$mount_point" && hdiutil detach "$dev"
}

mount_tmp_orphan() {
  hdiutil info | egrep 'image-path\s+: ram://' -A14 | egrep '^/dev/disk\d+\s*$'
}

process_argv "$@"
