#!/usr/bin/env ruby

exe = ENV['HOME'] + "/.wine/drive_c/Program Files/MT5 ActivTrades/terminal.exe"

unless File.executable? exe
  raise "MT5 not installed (expected at #{exe})"
end

fork do
  Dir.chdir '/'
  Process.setsid
  puts "[#{$$}] Launching #{exe}"
  $stdin.reopen '/dev/null'
  $stdout.reopen '/dev/null'
  $stderr.reopen '/dev/null'
  exec("wine", exe)
end
