#!/usr/bin/env bash

progname=$(basename "$0")
volume="WD6"

err=$(mntwd6 2>&1)
if [ $? != 0 ]; then
  terminal-notifier -title "$progname" -message "$err"
  exit 1
fi

terminal-notifier -title "$progname" -message "Opening ${volume}..."
exec open /Volumes/$volume
