#!/usr/bin/env ruby

##
# Wrapper over pyenv to add a `python` command that forwards to either python3
# or python depending on `pyenv version`.
#
# Allows to set global to 3.x and get pip3 while staying compatible with
# `python` shebangs such as one of the editorconfig plugins.
#

if `pyenv version` =~ /^3\./
  exec "python3", *ARGV
end

path = ENV['PATH'].to_s.split(":") - [__dir__]
ENV['PATH'] = path.join ":"

exec ENV['HOME']+"/.pyenv/shims/python", *ARGV
