#!/usr/bin/env bash

die() {
  echo "$@" >&2
  exit 1
}

[ ${#@} -ge 1 ] || die "usage: $0 <dir> [<version>]"

dir=$1
v=$2
[[ "$v" ]] || {
  dir_basename=$(ruby -rpathname -e "puts Pathname(ARGV[0]).expand_path.basename" "$dir")
  [ $? = 0 ] || die "failed to determine basename: ruby not installed?"
  v=${dir_basename#ruby-}
}

echo -n "Install v$v? [Y/n] "
read reply
[ "$reply" != "n" ] || exit 0

openssl_prefix() {
  brew --prefix openssl
}

readline_prefix() {
  brew --prefix readline
}

for n in openssl readline; do
  ${n}_prefix || die "Homebrew package '$n' not installed"
done

(cd "$dir" \
  && ./configure \
    --disable-install-doc \
    --prefix=$HOME/.rbenv/versions/$v \
    --with-openssl-dir=$(openssl_prefix) \
    --with-readline-dir=$(readline_prefix) \
  && make install -j8)
