#!/usr/bin/env ruby

def die(message)
  $stderr.puts message
  exit 1
end

line = `chrome-cli list links`.split("\n").find { |l| l =~ /\bsoundcloud\.com\// } \
  or die "SoundCloud tab not found"

tab_id = line[/:(\d+)/, 1] or raise "Unexpected lined format: %p" % line

exec "chrome-cli", "execute",
  "document.querySelector('.heroPlayButton').dispatchEvent(new Event('click'))",
  "-t", tab_id
