#!/usr/bin/env bash

CODE="$HOME/code"
PROJECTS="
  dotfiles
  bin
  services
"

UNDERLINE=$(tput smul)
NO_UNDERLINE=$(tput rmul)

for n in $PROJECTS; do
  echo -e "\n${UNDERLINE}$n${NO_UNDERLINE}" \
    && (cd "$CODE/$n" && git pull --rebase) \
    || exit 1
done
